### ISSUE TITLE
Enhance "sticks add" Command for Multiple Dependencies

### ISSUE THREAD

**Issue by mAmineChniti** [mAmineChniti/sticks#8]
**Description:**
The "sticks add" command currently supports adding a single dependency. To improve usability, we should enhance this command to support the addition of multiple dependencies in a single execution.

**Tasks:**

- [x] Update the "sticks add" command to accept and parse multiple dependencies.
- [x] Implement logic to handle the addition of each dependency making sure that there are no duplicate dependencies.
- [x] Ensure backward compatibility with the single dependency addition.

**Comment by mAmineChniti** [comment]
solved in #6
