### ISSUE TITLE
Implement CI/CD Pipeline for Automated Testing and Deployment

### ISSUE THREAD

**Issue by mAmineChniti** [mAmineChniti/sticks#9]
**Description:**
To streamline development processes, we need to establish a (CI/CD) pipeline for the project. This will automate testing, building, deployment, and release processes, improving efficiency and reliability.

**Tasks:**

- [x] Set up automated testing to run on each code push (use GitHub Actions).
- [x] Configure the pipeline for automatic building and packaging of the application.
- [x] Set up a release process for versioned releases.

**Comment by mAmineChniti** [comment]
1 & 2 solved in #11

**Comment by mAmineChniti** [comment]
3 solved in #12
